### ISSUE TITLE
配置文件放在用户目录下是否合理？

### ISSUE THREAD

**Issue by suren1986** [KscSDK/ksc-sdk-php#9]
说明文档中要求配置文件的位置是 ~\.ksyun\config
这增加了代码自动化部署的难度，如果放在项目的目录下，会更合理些。

**Comment by maigoxin** [comment]
谢谢意见， 目前如果要和项目相关联 建议通过接口把aksk传递进去。关于您的建议，近期会考虑添加相关功能

**Comment by suren1986** [comment]
我看到 README 最后传入 AccessKey 和 SecretKey 的方法了，谢谢！
